Homework 19
KatherinaKulinich/JavaScriptCourse--homeworks--hillel pull request #11
Opened 2022-10-30 19:46 UTC by KatherinaKulinich

2022-10-31 16:53 UTC, vb-oiko commented on homework-19.js
> +    fullName() {
```suggestion
    getFullName() {
```

ось хороший документ про неймінг https://github.com/kettanaito/naming-cheatsheet

2022-10-31 16:55 UTC, vb-oiko commented on homework-19.js
> +        this.persons = 0;
я б всеж таки додав у властивості масив обʼєктів класу Мешканець та метод для додавання мешканця до квартири

2022-10-31 18:29 UTC, vb-oiko requested changes
Що потрібно зробити

1. Створити клас Людина
    властивості 
        імʼя
        стать
    методи
        конструктор, який приймає два параметри: імʼя та стать
2. клас Квартира
    властивості 
        конструктор не потрібен
        масив жителів, який при створенні пустий
    методи 
        додати жителя - метод повинен приймати екземпляр класу Людина, та додавати до масиву жителів
3. клас Будинок 
    властивості 
        масив квартир, який при створенні пустий
        максимальна кількість квартир
    методи
        конструктор, який приймає один параметр: максимальну кількість квартир
        додати квартиру - метод повинен приймати екземпляр класу Квартира, перевіряти, чи не буде кількість перевищувати максимальну кількість квартир, і якщо це так, додати квартиру, в іншому випадку виводить у консоль відповідне повідомлення

в якості демонстраціїї створити:
    декілька екземплярів класу Людина
    декілька екземплярів класу Квартира
    додадити екземпляри класу Людина до екземплярів класу Квартира
    екземпляр класу Будинок
    додадити екземпляри класу Квартира до екземплярів класу Будинок

2022-11-03 07:56 UTC, vb-oiko commented on homework-19.js
> +        return console.warn('house is full');
Ви повертаєте результат виклнання логування, що дорівнює `undefined`.
Якщо це не помилка, краще було написати це двома окремими твердженнями

2022-11-03 07:57 UTC, vb-oiko commented on homework-19.js
> +    floors = 6;
навіщо ці властивості, якщо Ви ніде їх не використовуєте?

2022-11-03 07:57 UTC, vb-oiko approved these changes

2022-11-03 13:36 UTC, KatherinaKulinich commented on homework-19.js
> +        return console.warn('house is full');
так, дякую, виправлю

2022-11-03 13:37 UTC, merged